server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/quanlythuvien
spring.datasource.username=duy
spring.datasource.password=1712006
spring.datasource.driver-class-name=org.postgresql.Driver